#!/bin/bash
set -euo pipefail

### Normalize path -- all work should be relative to this script's location.
## Set up gopath -- also relative to this dir, so we work in isolation.
cd "$( dirname "${BASH_SOURCE[0]}" )"
export GOPATH="$PWD/.gopath/"

profPath="$GOPATH/tmp/prof/" ; mkdir -p "$profPath"
go test -i "$@"
echo "--- regular bench ---"
go test -run=XXX -bench=. "$@"
echo
echo "--- NOGC bench ---"
GOGC=off go test -run=XXX -bench=. "$@"
echo
echo "--- bench mem ---"
go test -run=XXX -bench=. -benchmem "$@"
